import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavBar from "./components/sideNavBar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hella Business",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideNavBar />
        <div className="mt-32 ml-80 mr-16 mb-16">
          {children}
        </div>
      </body>
    </html>
  );
}
